apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvisual-backend
  namespace: graduacion
---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvisual-deploy
  namespace: graduacion
  labels:
    name: cvisual-deploy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 168.232.79.90
    path: "/proyecto/cvisual/backend"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvisual-deploy
  namespace: graduacion
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: cvisual-deploy
---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvisual-server
  namespace: graduacion
  labels:
    run: cvisual-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cvisual-server
  template:
    metadata:
      labels:
        run: cvisual-server
    spec:
      containers:
        - name: cvisual-server
          image: oberd/php-8.0-apache:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/app"
              name: vol-php-backend
      volumes:
          - name: vol-php-backend
            persistentVolumeClaim:
              claimName: cvisual-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: cvisual-server
  namespace: graduacion
  labels:
    app.kubernetes.io/name: cvisual-server
    app.kubernetes.io/part-of: cvisual-server
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30010
      protocol: TCP
  selector:
    run: cvisual-server