apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvisual-frontend
  namespace: graduacion

---
# VOLUME DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvisual-deploy-frontend
  namespace: graduacion
  labels:
    name: cvisual-deploy-frontend
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 168.232.79.90
    path: "/proyecto/cvisual/frontend"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvisual-deploy-frontend
  namespace: graduacion
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: cvisual-deploy-frontend
---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvisual-server-front
  namespace: graduacion
  labels:
    run: cvisual-server-front
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cvisual-server-front
  template:
    metadata:
      labels:
        run: cvisual-server-front
    spec:
      containers:
        - name: cvisual-server-front
          image: jjolon/cvisualf:2.0.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/www/html"
              name: vol-php-frontend
      volumes:
        - name: vol-php-frontend
          persistentVolumeClaim:
            claimName: cvisual-deploy-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: cvisual-server-front
  namespace: graduacion
  labels:
    app.kubernetes.io/name: cvisual-server-front
    app.kubernetes.io/part-of: cvisual-server-front
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30011
      protocol: TCP
  selector:
    run: cvisual-server-front