apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvisual-frontend
  namespace: graduacion
---
# DEPLOYMENT APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvisual-server-front
  namespace: graduacion
  labels:
    run: cvisual-server-front
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cvisual-server-front
  template:
    metadata:
      labels:
        run: cvisual-server-front
    spec:
      containers:
        - name: cvisual-server-front
          image: jjolon/cvisual:1.0.3
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "700m"
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cvisual-server-front
  namespace: graduacion
  labels:
    app.kubernetes.io/name: cvisual-server-front
    app.kubernetes.io/part-of: cvisual-server-front
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30011
      protocol: TCP
  selector:
    run: cvisual-server-front